# Generated by Django 5.2.7 on 2025-10-21 17:06

import GoodBite.models
import GoodBite.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodBite', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=GoodBite.models.profile_image_path, validators=[GoodBite.validators.ValidateImageFile()]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=GoodBite.models.product_image_path, validators=[GoodBite.validators.ValidateImageFile()]),
        ),
    ]
