# Generated by Django 5.2.8 on 2025-11-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodBite', '0004_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
