# Generated by Django 5.2.8 on 2025-11-23 13:21

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodBite', '0005_product_initial_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Ejemplo: +34666123456', max_length=20, null=True, region='ES', unique=True),
        ),
    ]
